spring:
  application:
    name: language-forest
  datasource:
    url: "${DB_URL}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
          characterEncoding: utf8mb4
          useUnicode: true

  flyway:
    baseline-on-migrate: true
    enabled: false
    locations: classpath:db/migration

  data:
    redis:
      port: 6379
      host: localhost

openai:
  api-key: "${OPENAI_API_KEY}"
  base-url: https://api.openai.com/v1/chat/completions

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
      flywaydb: DEBUG
      hibernate:
        SQL: DEBUG  # SQL 실행 로그
        type:
          descriptor.sql.BasicBinder: TRACE  # SQL 파라미터 바인딩 값 로그
          descriptor.sql: TRACE  # Hibernate 내부 SQL 변환 과정 로깅